"""Download BTCUSDT 1h candles from Binance's public market-data API.

Usage:  python tools/fetch_data.py [--hours 2400] [--symbol BTCUSDT] [--out path]
Writes: dist/data/candles.js  (an ES module the app imports) unless --out is given

Standard library only. No API key needed.
"""
import argparse, json, time, urllib.request
from pathlib import Path

HOSTS = ["https://data-api.binance.vision", "https://api.binance.com"]
OUT = Path(__file__).resolve().parent.parent / "dist" / "data" / "candles.js"


def get(path):
    last = None
    for host in HOSTS:
        try:
            with urllib.request.urlopen(host + path, timeout=20) as r:
                return json.load(r)
        except Exception as e:  # try the next host
            last = e
    raise SystemExit(f"could not reach Binance: {last}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hours", type=int, default=2400)
    ap.add_argument("--symbol", default="BTCUSDT")
    ap.add_argument("--out", type=Path, default=OUT, help="output module (default: dist/data/candles.js)")
    a = ap.parse_args()

    rows, end = [], None
    while len(rows) < a.hours:
        q = f"/api/v3/klines?symbol={a.symbol}&interval=1h&limit=1000"
        if end is not None:
            q += f"&endTime={end}"
        batch = get(q)
        if not batch:
            break
        rows = batch + rows
        end = batch[0][0] - 1
        time.sleep(0.2)
    rows = rows[-a.hours:]
    # drop the still-open last candle
    if rows and rows[-1][6] > time.time() * 1000:
        rows = rows[:-1]

    candles = [[r[0] // 1000, float(r[1]), float(r[2]), float(r[3]), float(r[4]), round(float(r[5]), 3)] for r in rows]
    meta = {"symbol": a.symbol, "interval": "1h", "source": "Binance public klines", "count": len(candles),
            "from": candles[0][0], "to": candles[-1][0]}
    a.out.parent.mkdir(parents=True, exist_ok=True)
    body = ",\n".join(json.dumps(c, separators=(",", ":")) for c in candles)
    a.out.write_text(
        "// Generated by tools/fetch_data.py. Rows: [unixSeconds, open, high, low, close, volume]\n"
        f"export const META = {json.dumps(meta)};\n"
        f"export const CANDLES = [\n{body}\n];\n",
        encoding="utf-8",
    )
    print(f"wrote {len(candles)} candles -> {a.out}")


if __name__ == "__main__":
    main()
